-- Create profiles table linked to auth.users
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  age int,
  gender text check (gender in ('Masculino', 'Femenino', 'Otro')),
  city text,
  brushing_frequency text,
  smoker boolean default false,
  has_caries_or_fracture boolean default false,
  created_at timestamptz default now()
);

-- Enable RLS for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create sensitivity_logs table
create table sensitivity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  vas_score int check (vas_score >= 0 and vas_score <= 10),
  triggers text[], -- Array of strings e.g. ['Cold', 'Sweet']
  qol_impact text check (qol_impact in ('Nada', 'Poco', 'Mucho')),
  created_at timestamptz default now()
);

-- Enable RLS for sensitivity_logs
alter table sensitivity_logs enable row level security;

create policy "Users can view own logs." on sensitivity_logs
  for select using (auth.uid() = user_id);

create policy "Users can insert own logs." on sensitivity_logs
  for insert with check (auth.uid() = user_id);

-- Function to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile on sign up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
