-- Create learning_progress table to track read articles
create table learning_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  article_id text not null,
  created_at timestamptz default now(),
  unique(user_id, article_id)
);

-- Enable RLS
alter table learning_progress enable row level security;

-- Policies
create policy "Users can view own learning progress." on learning_progress
  for select using (auth.uid() = user_id);

create policy "Users can insert own learning progress." on learning_progress
  for insert with check (auth.uid() = user_id);

create policy "Users can delete own learning progress." on learning_progress
  for delete using (auth.uid() = user_id);
